routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', 'CustomerController@index')->name('home');
Route::resource('customer','CustomerController');
Route::group(['middleware' => 'is_admin'], function () {
    Route::get('admin/home', 'HomeController@adminHome')->name('admin.home');
    Route::resource('admin/service','ServiceController');
    Route::resource('admin/booking','BookingController');
    Route::resource('admin/user','UserController');
 });

app/Booking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    protected $fillable = ['customer_id', 'status', 'author_id'];

    public function customer()
    {
      return $this->belongsTo(Customers::class);
    }
}

app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Booking;
use App\Customers;
use App\Services;
use App\Cars;

class BookingController extends Controller
{
    public function __construct()
    {
        $this->middleware('is_admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bookings = Booking::with('customer')->get();
        return view('backend.booking.index',compact('bookings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $services = Services::all();
        return view('backend.booking.create',compact('services'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedCustomer = $this->validateCustomer($request);
        $validatedCustomer['barcode_no'] = $this->generateBarcodeNumber();
        $customer = Customers::create($validatedCustomer + ['author_id' => auth()->id()]);
        $validatedCar = $this->validateCar($request);
        $validatedCar['customer_id'] = $customer->id;
        Cars::create($validatedCar + ['author_id' => auth()->id()]);
        $customer->service()->sync($request->services ,false);
        $bookingData['customer_id'] = $customer->id;
        Booking::create($bookingData + ['author_id' => auth()->id()]);
        // send sms after booking
        $basic  = new \Nexmo\Client\Credentials\Basic('9c070f19', 'DeQ5J9eELTOgLvMo');
        $client = new \Nexmo\Client($basic);
        $message = $client->message()->send([
          'to' => $customer->phone,
          'from' => 'Auto Verge',
          'text' => 'Enjoy. Your booking id is ' . $customer->barcode_no
        ]);
        return redirect()->route('booking.index')->with('success', 'Date is successfully saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Booking $booking)
    {
        $booking = Booking::with('customer')->findOrFail($booking->id);
        $services = Services::all();
        return view('backend.booking.edit', compact('booking','services'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatebooking = $this->validateBooking($request);
        $validatecustomer = $this->validateCustomer($request);
        $phone = $validatecustomer['phone'];
        Booking::whereId($id)->update($validatebooking + ['author_id' => auth()->id()]);
        $customer = Customers::find($id);
        if (isset($request->services)) {
            $customer->service()->sync($request->services);
        }else{
            $customer->service()->sync(array());
        }
        $customer->update($validatecustomer + ['author_id' => auth()->id()]);
        // send sms after receive price
        $basic  = new \Nexmo\Client\Credentials\Basic('9c070f19', 'DeQ5J9eELTOgLvMo');
        $client = new \Nexmo\Client($basic);
        $message = $client->message()->send([
          'to' => $phone,
          'from' => 'Auto Verge',
          'text' => 'Thanks for using our services.'
        ]);
        return redirect()->route('booking.index')->with('success', 'Data is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $booking = Booking::findOrFail($id);
      $booking->delete();
      return redirect()->route('booking.index')->with('success', 'Data is successfully deleted');
    }

    public function validateBooking($request)
    {
        return $request->validate([
            'status' => 'required|integer'
        ]);
    }

    public function validateCustomer($request)
    {
        return $request->validate([
            'name' => 'required|string|max:125',
            'email' => 'required|email',
            'phone' => 'required',
            'from_date' => 'required',
            'to_date' => 'required',
            'note' => 'required'
        ]);
    }

    public function validateCar($request)
    {
        return $request->validate([
            'car_name' => 'required',
            'reg_no' => 'required',
            'model' => 'required',
        ]);
    }

    public function generateBarcodeNumber()
    {
        $number = mt_rand(1000000000, 9999999999);
        if ($this->barcodeNumberExists($number)) {
            return generateBarcodeNumber();
        }
        return $number;
    }

    public function barcodeNumberExists($number)
    {
        return Customers::where('barcode_no')->exists();
    }
}

resources/views/backend/booking/create.blade.php
@extends("dashboard.master")

@section ("header")

    <strong>Add Booking</strong>

@endsection

@section ('breadcrumb-li')

    <li class="active">Add Booking</li>

@endsection

@section("content")
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        @if ($errors->any())
          <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
            </ul>
          </div>
        @endif
        <form method="post" action="{{ route('booking.store') }}">
          @csrf
          <h3>Customer Detail</h3>
          <div class="form-group">
              <label>Name:</label>
              <input type="text" name="name" placeholder="Name" class="form-control">
          </div>
          <div class="form-group">
              <label>Email:</label>
              <input type="email" name="email" placeholder="Email" class="form-control">
          </div>
          <div class="form-group">
              <label>Phone:</label>
              <input type="text" name="phone" placeholder="Phone" class="form-control">
          </div>
          <hr>
          <h3>Car Detail</h3>
          <div class="form-group">
              <label>Car Number:</label>
              <input type="text" name="car_name" placeholder="Car No:" class="form-control">
          </div>
          <div class="form-group">
              <label>Car Reg No:</label>
              <input type="text" name="reg_no" placeholder="Reg No:" class="form-control">
          </div>
          <div class="form-group">
              <label>Model No:</label>
              <input type="text" name="model" placeholder="Model No:" class="form-control">
          </div>
          <hr>
          <div class="form-group">
              <label>Select Date:</label>
              <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                       <input class="date form-control" type="text" placeholder="Start Date" name="from_date">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <input class="date form-control" type="text" placeholder="End Date" name="to_date">
                    </div>
                  </div>
              </div>
          </div>
          <div class="form-group">
              <label>Addtional services:</label>
              <select class="select2-multi-form form-control" name="services[]" multiple="multiple">
                @foreach($services as $service)
                  <option value="{{$service->id}}">{{$service->name}}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
              <label>Note:</label>
              <textarea class="form-control" name="note" rows="3"></textarea>
          </div>
          <a href="{{ route('booking.index') }}" class="btn btn-info">Back</a>
          <button type="submit" class="btn btn-success">Submit</button>
        </form>
  		</div>
</div>
@endsection

resources/views/backend/booking/edit.blade.php
@extends("dashboard.master")

@section ("header")

    <strong>Edit Booking</strong>

@endsection

@section ('breadcrumb-li')

    <li class="active">Edit Booking</li>

@endsection

@section("content")
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        @if ($errors->any())
          <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
            </ul>
          </div>
        @endif
        <form method="post" action="{{ route('booking.update', $booking->id ) }}">
          @csrf
          @method('PATCH')
            <div class="form-group">
                <label>Booking Id:</label>
                <input type="text" class="form-control" name="name" value="{{ $booking->customer->barcode_no }}" disabled/>
            </div>
            <div class="form-group">
                <label>Status</label>
                <select class="form-control" name="status">
                  <option value="option" disabled selected>Select Status</option>
                  <option value="0" {{$booking->status== 0  ? 'selected' : ''}}>Pending</option>
                  <option value="1" {{$booking->status== 1  ? 'selected' : ''}}>Paid</option>
                </select>
              </div>
            <div class="form-group">
                <label>Customer Name:</label>
                <input type="text" class="form-control" name="name" value="{{ $booking->customer->name }}"/>
            </div>
            <div class="form-group">
                <label>email:</label>
                <input type="email" class="form-control" name="email" value="{{ $booking->customer->email }}"/>
            </div>
            <div class="form-group">
                <label>Phone:</label>
                <input type="text" class="form-control" name="phone" value="{{ $booking->customer->phone }}"/>
            </div>
            <div class="form-group">
                <label>From Date:</label>
                <input class="date form-control" type="text" placeholder="Start Date" name="from_date" value="{{ $booking->customer->from_date }}">
            </div>
            <div class="form-group">
                <label>To Date:</label>
                <input class="date form-control" type="text" placeholder="End Date" name="to_date" value="{{ $booking->customer->to_date }}">
            </div>
            <div class="form-group">
                <label>Note:</label>
                <textarea class="form-control" name="note" rows="3">{{$booking->customer->note}}</textarea>
            </div>
            <div class="form-group">
                <label>Addtional services:</label>
                <select class="select2-multi-form form-control" name="services[]" multiple="multiple">
                  @foreach($services as $service)
                    <option value="{{$service->id}}">{{$service->name}}</option>
                  @endforeach
                </select>
            </div>
            <div class="form-group">
              <a href="{{ route('booking.index') }}" class="btn btn-info">Back</a>
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
      </form>
  		</div>
</div>
@endsection

resources/views/backend/booking/index.blade.php
@extends("dashboard.master")

@section ("header")

    <strong>Bookings</strong>
    <a href="{{ route('booking.create') }}" class="btn btn-info">Add</a>

@endsection

@section ('breadcrumb-li')

    <li class="active">Bookings</li>

@endsection

@section("content")
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="box box-primary">
          <div class="box-body">
              <div class="dataTables_wrapper form-inline dt-bootstrap">
                  <div class="table-responsive">
                    @if(session()->get('success'))
                      <div class="alert alert-success alert-dismissable">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                          </button>
                          {{session('success')}}
                      </div>
                    @endif

                    @if(session()->get('error'))
                        <div class="alert alert-error alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{session('error')}}
                        </div>
                    @endif
                    <table class="table table-bordered table-hover dataTable">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Booking ID</th>
                          <th>Name</th>
                          <th>Date From</th>
                          <th>Date To</th>
                          <th>Duration Date</th>
                          <th>Services</th>
                          <th>Status</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php $i=1; ?>
                        @foreach( $bookings as $result )
                        <tr>
                        <td>{{ $i++ }}</td>
                        <td>{{ $result->customer->barcode_no }}</td>
                        <td>{{ $result->customer->name }}</td>
                        <td>{{ $result->customer->from_date }}</td>
                        <td>{{ $result->customer->to_date }}</td>
                        <?php
                            $date1 = date_create($result->customer->from_date);
                            $date2 = date_create($result->customer->to_date);
                            $diff = date_diff($date1,$date2);
                        ?>
                        <td>{{ $diff->format("%a days") }}</td>
                        <td>
                            @foreach ($result->customer->service as $value)
                                {{$value->name}}
                            @endforeach
                        </td>
                        <td>
                          @if ( $result["status"] == 0 )
                            <span class="badge badge-warning">Pending</span>
                          @elseif ( $result["status"] == 1 )
                            <span class="badge badge-success">Paid</span>
                          @else
                            <span class="badge badge-danger">Reject</span>
                          @endif
                        </td>
                        <td>
                            <ul class="list-inline">
                              <li class="list-inline-item">
                                <a href="{{ route('booking.edit', $result->id) }}" class="btn btn-warning"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                              </li>
                              <li class="list-inline-item">
                                <form action="{{ route('booking.destroy', $result->id) }}" class="delete_form" method="post">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                </form>
                              </li>
                            </ul>
                        </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
              </div>
          </div>
      </div>
</div>
</div>
@endsection