routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', 'CustomerController@index')->name('home');
Route::resource('customer','CustomerController');
Route::group(['middleware' => 'is_admin'], function () {
    Route::get('admin/home', 'HomeController@adminHome')->name('admin.home');
    Route::resource('admin/service','ServiceController');
    Route::resource('admin/booking','BookingController');
    Route::resource('admin/user','UserController');
 });

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','phone','is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('is_admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $user)
    {
        if(auth()->id() != 1) {
          $users = User::where('is_admin',auth()->id())->get();
        } else {
          $users = User::all();
        }
        return view('backend.users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $this->validateUser($request);
        $validatedData['password'] = \Hash::make($validatedData['password']);
        User::create($validatedData);

        return redirect()->route('user.index')->with('success', 'Date is successfully saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('backend.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $this->validateUser($request);
        $validatedData['password'] = \Hash::make($validatedData['password']);
        User::whereId($id)->update($validatedData);
        return redirect()->route('user.index')->with('success', 'Data is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return redirect()->route('user.index')->with('success', 'Data is successfully deleted');
    }

    public function validateUser($request)
    {
        return $request->validate([
            'name' => 'required|string|max:125',
            'email' => 'required|email',
            'password' => 'required|min:8',
            'phone' => 'required',
            'is_admin' => 'required',
        ]);
    }
}

resources/views/backend/users/create.blade.php
@extends("dashboard.master")

@section ("header")

    <strong>Add user</strong>

@endsection

@section ('breadcrumb-li')

    <li class="active">Add user</li>

@endsection

@section("content")
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        @if ($errors->any())
          <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
            </ul>
          </div>
        @endif
        <form method="post" action="{{ route('user.store') }}">
          @csrf
          <div class="form-group">
              <label>Name:</label>
              <input type="text" class="form-control" name="name"/>
          </div>
          <div class="form-group">
              <label>Email:</label>
              <input type="text" class="form-control" name="email" />
          </div>
          <div class="form-group">
              <label>Password:</label>
              <input type="password" class="form-control" name="password"/>
          </div>
          <div class="form-group">
              <label>Phone:</label>
              <input type="text" class="form-control" name="phone"/>
          </div>
          <div class="form-group">
              <label>Role:</label>
              <select class="form-control" name="is_admin">
                <option value="option" disabled selected>Select Role</option>
                <option value="1">Admin</option>
                <option value="2">User</option>
              </select>
          </div>
          <a href="{{ route('user.index') }}" class="btn btn-info">Back</a>
          <button type="submit" class="btn btn-success">Submit</button>
      </form>
  		</div>
</div>
@endsection

resources/views/backend/users/edit.blade.php
@extends("dashboard.master")

@section ("header")

    <strong>Edit user</strong>

@endsection

@section ('breadcrumb-li')

    <li class="active">Edit user</li>

@endsection

@section("content")
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        @if ($errors->any())
          <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
            </ul>
          </div>
        @endif
        <form method="post" action="{{ route('user.update', $user->id ) }}">
          @csrf
          @method('PATCH')
          <div class="form-group">
              <label>Name:</label>
              <input type="text" class="form-control" name="name" value="{{ $user->name }}"/>
          </div>
          <div class="form-group">
              <label>Email:</label>
              <input type="text" class="form-control" name="email" value="{{ $user->email }}"/>
          </div>
          <div class="form-group">
              <label>Password:</label>
              <input type="password" class="form-control" name="password" value="{{ $user->password }}"/>
          </div>
          <div class="form-group">
              <label>Phone:</label>
              <input type="text" class="form-control" name="phone" value="{{ $user->phone }}"/>
          </div>
          <div class="form-group">
              <label>Role:</label>
              <select class="form-control" name="is_admin">
                <option value="option" disabled selected>Select Role</option>
                <option value="1" {{$user->is_admin== 1  ? 'selected' : ''}}>Admin</option>
                <option value="2" {{$user->is_admin== 2  ? 'selected' : ''}}>User</option>
              </select>
          </div>
          <a href="{{ route('user.index') }}" class="btn btn-info">Back</a>
          <button type="submit" class="btn btn-primary">Update</button>
      </form>
  		</div>
</div>
@endsection

resources/views/backend/users/index.blade.php
@extends("dashboard.master")

@section ("header")

    <strong>Users</strong>
    <a href="{{ route('user.create') }}" class="btn btn-info">Add</a>

@endsection

@section ('breadcrumb-li')

    <li class="active">Useers</li>

@endsection

@section("content")
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="box box-primary">
          <div class="box-body">
              <div class="dataTables_wrapper form-inline dt-bootstrap">
                  <div class="table-responsive">
                    @if(session()->get('success'))
                      <div class="alert alert-success alert-dismissable">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                          </button>
                          {{session('success')}}
                      </div>
                    @endif

                    @if(session()->get('error'))
                        <div class="alert alert-error alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{session('error')}}
                        </div>
                    @endif
                    <table class="table table-bordered table-hover dataTable">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Name</th>
                          <th>Email</th>
                          <th>Phone</th>
                          <th>Role</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php $i=1; ?>
                        @foreach($users as $result)
                        <tr>
                        <td>{{ $i++ }}</td>
                        <td>{{ $result["name"] }}</td>
                        <td>{{ $result["email"] }}</td>
                        <td>{{ $result["phone"] }}</td>
                        <td>
                          @if ( $result["is_admin"] == 1 )
                            <span class="badge badge-warning">Admin</span>
                          @elseif ( $result["is_admin"] == 2 )
                            <span class="badge badge-success">User</span>
                          @else
                              <span class="badge badge-info">Customer</span>
                          @endif
                        </td>
                        <td>
                            <ul class="list-inline">
                              <li class="list-inline-item">
                                <a href="{{ route('user.edit', $result->id) }}" class="btn btn-warning"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                              </li>
                              <li class="list-inline-item">
                                <form action="{{ route('user.destroy', $result->id) }}" class="delete_form" method="post">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                </form>
                              </li>
                            </ul>
                        </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
              </div>
          </div>
      </div>
</div>
</div>
@endsection