routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', 'CustomerController@index')->name('home');
Route::resource('customer','CustomerController');
Route::group(['middleware' => 'is_admin'], function () {
    Route::get('admin/home', 'HomeController@adminHome')->name('admin.home');
    Route::resource('admin/service','ServiceController');
    Route::resource('admin/booking','BookingController');
    Route::resource('admin/user','UserController');
 });

app/Services.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Services extends Model
{
  protected $fillable = ['name','author_id'];

  public function customer()
  {
      return $this->belongsToMany(Customers::class,'customer_service','servcie_id','customer_id');
  }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services;

class ServiceController extends Controller
{
    public function __construct()
    {
        $this->middleware('is_admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Services $service)
    {
        if($service->author_id != 1) {
          $services = Services::where('author_id',auth()->id())->get();
        } else {
          $services = Services::all();
        }
        return view('backend.services.index',compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $this->validateService($request);
        Services::create($validatedData + ['author_id' => auth()->id()]);

        return redirect()->route('service.index')->with('success', 'Date is successfully saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $service = Services::findOrFail($id);
        return view('backend.services.edit',compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $this->validateService($request);
        Services::whereId($id)->update($validatedData + ['author_id' => auth()->id()]);
        return redirect()->route('service.index')->with('success', 'Data is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $service = Services::findOrFail($id);
        $service->delete();
        return redirect()->route('service.index')->with('success', 'Data is successfully deleted');
    }

    public function validateService($request)
    {
        return $request->validate([
            'name' => 'required|string|max:125'
        ]);
    }
}

resources/views/backend/services/create.blade.php
@extends("dashboard.master")

@section ("header")

    <strong>Add Service</strong>

@endsection

@section ('breadcrumb-li')

    <li class="active">Add Service</li>

@endsection

@section("content")
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        @if ($errors->any())
          <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
            </ul>
          </div>
        @endif
        <form method="post" action="{{ route('service.store') }}">
          @csrf
          <div class="form-group">
              <label>Name:</label>
              <input type="text" class="form-control" name="name"/>
          </div>
          <a href="{{ route('service.index') }}" class="btn btn-info">Back</a>
          <button type="submit" class="btn btn-success">Submit</button>
      </form>
  		</div>
</div>
@endsection

resources/views/backend/services/edit.blade.php
@extends("dashboard.master")

@section ("header")

    <strong>Edit Services</strong>

@endsection

@section ('breadcrumb-li')

    <li class="active">Edit Service</li>

@endsection

@section("content")
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        @if ($errors->any())
          <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
            </ul>
          </div>
        @endif
        <form method="post" action="{{ route('service.update', $service->id ) }}">
          @csrf
          @method('PATCH')
          <div class="form-group">
              <label>Name:</label>
              <input type="text" class="form-control" name="name" value="{{ $service->name }}"/>
          </div>
          <a href="{{ route('service.index') }}" class="btn btn-info">Back</a>
          <button type="submit" class="btn btn-primary">Update</button>
      </form>
  		</div>
</div>
@endsection

resources/views/backend/services/index.blade.php
@extends("dashboard.master")

@section ("header")

    <strong>Services</strong>
    <a href="{{ route('service.create') }}" class="btn btn-info">Add</a>

@endsection

@section ('breadcrumb-li')

    <li class="active">Services</li>

@endsection

@section("content")
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="box box-primary">
          <div class="box-body">
              <div class="dataTables_wrapper form-inline dt-bootstrap">
                  <div class="table-responsive">
                    @if(session()->get('success'))
                      <div class="alert alert-success alert-dismissable">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                          </button>
                          {{session('success')}}
                      </div>
                    @endif

                    @if(session()->get('error'))
                        <div class="alert alert-error alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{session('error')}}
                        </div>
                    @endif
                    <table class="table table-bordered table-hover dataTable">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Name</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php $i=1; ?>
                        @foreach($services as $result)
                        <tr>
                        <td>{{ $i++ }}</td>
                        <td>{{ $result["name"] }}</td>
                        <td>
                            <ul class="list-inline">
                              <li class="list-inline-item">
                                <a href="{{ route('service.edit', $result->id) }}" class="btn btn-warning"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                              </li>
                              <li class="list-inline-item">
                                <form action="{{ route('service.destroy', $result->id) }}" class="delete_form" method="post">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                </form>
                              </li>
                            </ul>
                        </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
              </div>
          </div>
      </div>
</div>
</div>
@endsection